@extends('layouts.app')

@section('content')
<div class="min-h-screen bg-slate-50 py-8">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="md:flex md:items-center md:justify-between mb-8">
            <div class="flex-1 min-w-0">
                <h2 class="text-3xl font-extrabold leading-7 text-slate-900 sm:text-4xl sm:truncate">AI Study Planner</h2>
                <p class="mt-2 text-sm text-slate-500">Your personalized, adaptive schedule generated by AI to maximize your learning efficiency.</p>
            </div>
            <div class="mt-4 flex md:mt-0 md:ml-4 space-x-3">
                <button type="button" class="inline-flex items-center px-4 py-2 border border-slate-300 rounded-lg shadow-sm text-sm font-medium text-slate-700 bg-white hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-emerald-500 transition">
                    Adjust Settings
                </button>
                <button type="button" class="inline-flex items-center px-4 py-2 border border-transparent rounded-lg shadow-sm text-sm font-medium text-white bg-emerald-600 hover:bg-emerald-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-emerald-500 transition">
                    Generate New Plan
                </button>
            </div>
        </div>

        <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
            <!-- Main Calendar/Timeline Area -->
            <div class="lg:col-span-2 space-y-6">
                <!-- Day View Card -->
                <div class="bg-white shadow-sm border border-slate-200 rounded-2xl overflow-hidden">
                    <div class="px-6 py-5 border-b border-slate-200 bg-slate-50 flex justify-between items-center">
                        <h3 class="text-lg leading-6 font-bold text-slate-900">Today's Schedule</h3>
                        <span class="inline-flex items-center px-3 py-0.5 rounded-full text-sm font-medium bg-emerald-100 text-emerald-800">
                            On Track
                        </span>
                    </div>
                    <ul role="list" class="divide-y divide-slate-200">
                        <!-- Task 1 -->
                        <li class="px-6 py-5 hover:bg-slate-50 transition">
                            <div class="flex items-center space-x-4">
                                <div class="flex-shrink-0">
                                    <span class="h-10 w-10 rounded-full bg-blue-100 flex items-center justify-center ring-8 ring-white">
                                        <svg class="h-5 w-5 text-blue-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
                                        </svg>
                                    </span>
                                </div>
                                <div class="flex-1 min-w-0">
                                    <p class="text-sm font-medium text-slate-900 truncate">Read Physics Chapter 4</p>
                                    <p class="text-sm text-slate-500">Thermodynamics Basics</p>
                                </div>
                                <div>
                                    <span class="inline-flex items-center text-sm text-slate-500">
                                        <svg class="mr-1.5 h-4 w-4 text-slate-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                                        </svg>
                                        10:00 AM - 11:30 AM
                                    </span>
                                </div>
                            </div>
                        </li>
                        <!-- Task 2 -->
                        <li class="px-6 py-5 hover:bg-slate-50 transition">
                            <div class="flex items-center space-x-4">
                                <div class="flex-shrink-0">
                                    <span class="h-10 w-10 rounded-full bg-purple-100 flex items-center justify-center ring-8 ring-white">
                                        <svg class="h-5 w-5 text-purple-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" />
                                        </svg>
                                    </span>
                                </div>
                                <div class="flex-1 min-w-0">
                                    <p class="text-sm font-medium text-slate-900 truncate">Math Practice Quiz</p>
                                    <p class="text-sm text-slate-500">Calculus Integration</p>
                                </div>
                                <div>
                                    <span class="inline-flex items-center text-sm text-slate-500">
                                        <svg class="mr-1.5 h-4 w-4 text-slate-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                                        </svg>
                                        12:00 PM - 1:00 PM
                                    </span>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>

            <!-- Sidebar -->
            <div class="space-y-6">
                <!-- AI Insights -->
                <div class="bg-gradient-to-br from-emerald-500 to-teal-600 rounded-2xl shadow-sm text-white p-6">
                    <h3 class="text-lg font-bold flex items-center mb-4">
                        <svg class="w-6 h-6 mr-2 opacity-80" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
                        </svg>
                        AI Recommendations
                    </h3>
                    <p class="text-sm text-emerald-50 leading-relaxed mb-4">Based on your recent performance, I've allocated more time to Calculus this week. You're doing great in Physics, so we can focus on practice problems there.</p>
                    <button class="w-full bg-white text-emerald-700 font-semibold py-2 px-4 rounded-lg shadow hover:bg-emerald-50 transition text-sm">
                        View Detailed Analysis
                    </button>
                </div>
                
                <!-- Weekly Goals -->
                <div class="bg-white shadow-sm border border-slate-200 rounded-2xl p-6">
                    <h3 class="text-md font-bold text-slate-900 mb-4">Weekly Goals</h3>
                    <div class="space-y-4">
                        <div>
                            <div class="flex justify-between text-sm font-medium text-slate-700 mb-1">
                                <span>Complete 5 Quizzes</span>
                                <span>3/5</span>
                            </div>
                            <div class="w-full bg-slate-200 rounded-full h-2">
                                <div class="bg-emerald-500 h-2 rounded-full" style="width: 60%"></div>
                            </div>
                        </div>
                        <div>
                            <div class="flex justify-between text-sm font-medium text-slate-700 mb-1">
                                <span>Study Hours</span>
                                <span>12/20 hrs</span>
                            </div>
                            <div class="w-full bg-slate-200 rounded-full h-2">
                                <div class="bg-emerald-500 h-2 rounded-full" style="width: 60%"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
